[build]
cmd = "go build -o ./tmp/main ./cmd/webserver/main.go"
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]

[watch]
# Paths to watch for changes
paths = ["./"]
# File extensions to watch
extensions = ["go"]
# Exclude paths or files from being watched
exclude = ["assets", "vendor", "tmp", "docker", ".git"]

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[server]
# Port to run the server on
port = 8080
