version: "2"
linters:
  enable:
    - exhaustive
    - exhaustruct
    - gochecksumtype
    - gosec
    - nilerr
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: warning
  rules:
    - linters:
        - exhaustruct
      severity: info
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
